---
- name: FreeIPA HBAC rules
  tags: freeipa_hbacrule
  community.general.ipa_hbacrule:
# CN is required and must be the unique identifier.
    cn: "{{ item.cn }}"
    description: "{{ item.description | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    hostcategory: "{{ item.hostcategory | default(omit) }}"
    hostgroup: "{{ item.hostgroup | default(omit) }}"
    ipa_host: "{{ common_primary_dc }}"
    ipa_port: 443
    ipa_prot: "https"
    ipa_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    service: "{{ item.service | default(omit) }}"
    servicecategory: "{{ item.servicecategory | default(omit) }}"
    servicegroup: "{{ item.servicegroup | default(omit) }}"
    sourcehost: "{{ item.sourcehost | default(omit) }}"
    sourcehostcategory: "{{ item.sourcehostcategory | default(omit) }}"
    sourcehostgroup: "{{ item.sourcehostgroup | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    usercategory: "{{ item.usercategory | default(omit) }}"
    usergroup: "{{ item.usergroup | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(auth_validate_certs) }}"
  loop: "{{ freeipa_hbacrule }}"
