---

- name: set short name for ldap_overlays.ldap_memberof.overlay
  ansible.builtin.set_fact:
    lmo: "{{ ldap_overlays.ldap_memberof.overlay }}"
  when: common_full_hostname == common_primary_dc
  tags: ldap_setup_memberof

- name: add entry of memberof overlay into LDAP
  community.general.ldap_entry:
    dn: "{{ lmo.dn }}"
    objectClass:
      - "olcOverlayConfig"
      - "olcMemberOf"
    attributes:
        olcMemberOfGroupOC: "{{ lmo.attrs.olcMemberOfGroupOC }}"
        olcMemberOfMemberAD: "{{ lmo.attrs.olcMemberOfMemberAD }}"
        olcMemberOfMemberOfAD: "{{ lmo.attrs.olcMemberOfMemberOfAD }}"
        olcMemberOfDangling: "{{ lmo.attrs.olcMemberOfDangling | default(omit) }}"
        olcMemberOfDanglingError: "{{ lmo.attrs.olcMemberOfDanglingError | default(omit) }}"
        olcMemberOfRefInt: "{{ lmo.attrs.olcMemberOfRefInt }}"
  when: common_full_hostname == common_primary_dc
  tags: ldap_setup_memberof

