---
- name: Add sudo entries to ldap
  community.general.ldap_entry:
    dn: "{{ item.value.dn }}"
    objectClass:
    - "{{ item.value.objectClass }}"
    attributes:
      cn: "{{ item.value.cn }}"
      description: "{{ item.value.description | default(omit) }}"
  loop: "{{  lookup('ansible.builtin.dict', ldap_sudo, wantlist=True) }}"
  tags: ldap_setup_tree,ldap_setup_sudo,ldap_sudo_add
- name: Change sudoOption of sudo_ldap entries
  community.general.ldap_attrs:
    dn: "{{ item.0.value.dn }}"
    attributes:
      sudoOption: "{{ item.1 | default (omit) }}"
  loop: "{{  lookup('ansible.builtin.dict', ldap_sudo, wantlist=True) | subelements('value.sudoOption',skip_missing=True) }}"
  tags: ldap_setup_tree,ldap_setup_sudo,ldap_sudo_options
- name: Change attributes of sudo_ldap entries
  community.general.ldap_attrs:
    dn: "{{ item.value.dn }}"
    attributes:
      sudoUser: "{{ item.value.sudoUser | default(omit) }}"
      sudoHost: "{{ item.value.sudoHost | default(omit) }}"
      sudoCommand: "{{ item.value.sudoCommand | default(omit) }}"
      sudoRunAsUser: "{{ item.value.sudoRunAsUser | default (omit) }}"
      sudoRunAsGroup: "{{ item.value.sudoRunAsGroup | default (omit) }}"
      sudoNotBefore: "{{ item.value.sudoNotBefore | default (omit) }}"
      sudoNotAfter: "{{ item.value.sudoNotAfter | default (omit) }}"
      sudoOrder: "{{ item.value.sudoOrder }}"
  loop: "{{  lookup('ansible.builtin.dict', ldap_sudo, wantlist=True) }}"
  tags: ldap_setup_tree,ldap_setup_sudo,ldap_sudo_attrs
