---
- name: Check if ansible version is equal or greater than 2.11
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"
  when: ansible_version.full is ansible.builtin.version('2.11','<')

- name: Check if python is equal or greater than 3
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"
  when: ansible_python.version.major is ansible.builtin.version('3','<')

- name: Set distro independed variables
  ansible.builtin.include_vars:
    file: "{{ auth_vars_dir }}/main.yml"
  tags: auth_set_vars,auth_install

- name: Set distro depended variables
  ansible.builtin.include_vars:
    file: "{{ auth_vars_dir }}/{{ ansible_pkg_mgr }}.yml"
  tags: auth_set_vars,auth_install

- name: Install auth services
  ansible.builtin.package:
    name: "{{ auth_packages }}"
    state: present
  tags: auth_install

- name: Check if local CA is exist on target host
  ansible.builtin.stat:
    path: "{{ common_ssl_CA }}"
  register: stat_ssl_ca
  tags: auth_ssl_ca

- name: Copy root CA to target host
  ansible.builtin.copy:
    src: "{{ common_local_store }}/{{ common_domain_name }}-ssl-ca.pem"
    dest: "{{ common_ssl_CA }}"
    owner: "root"
    group: "root"
    mode: 0644
  when: ! stat_ssl_ca.stat.exists
  tags: auth_ssl_ca

- name: Setup authdb server (default OpenLDAP)
  ansible.builtin.include_tasks: "{{ auth_db }}.yml" 
  when: ldap_servers_group in group_names
  tags: auth_db_setup

- name: Edit {{ ldap_config_dir }}/ldap.conf (system config)
  ansible.builtin.lineinfile:
    path:  "{{ ldap_config_dir }}/ldap.conf"
    regexp: "^[\t ]*#?[\t ]*{{ item.key }}.*"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    create: true
  loop: "{{ lookup('ansible.builtin.dict', ldap_conf_params, wantlist=True) }}"
  tags: ldap_client_config

- name: Edit /etc/ldap.conf (any services and users config)
  ansible.builtin.lineinfile:
    path:  "/etc/ldap.conf"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    owner: 'root'
    group: 'root'
    mode: '0600'
    create: true
  loop: "{{ lookup('ansible.builtin.dict', ldap_conf_params, wantlist=True) }}"
  tags: ldap_client_config

- name: Configure auth protocol if auth_proto is not ldap (default krb5)
  ansible.builtin.include_tasks: "{{ auth_proto }}.yml" 
  when: auth_proto != "ldap" and auth_proto != "freeipa"
  tags: auth_proto_setup

- name: Configure auth service if auth_daemon is not ldap (default sssd)
  ansible.builtin.include_tasks: "{{ auth_daemon }}.yml" 
  when: auth_daemon != "ldap" and auth_proto != "freeipa"
  tags: auth_daemon_setup

- name: Add passwd/shadow/group over {{ auth_daemon }} into /etc/nsswitch.conf
  ansible.builtin.lineinfile:
    path: "/etc/nsswitch.conf"
    regexp: "{{ item }}"
    line: '\1:\2{{ auth_daemon | regex_replace("sssd","sss") }} \3'
    state: present
    backrefs: yes
  loop:
    - "^(passwd):([ \t]*).*(files).*$"
    - "^(shadow):([ \t]*).*(files([ \t][[][^]]*[\\]])?).*$"
    - "^(group):([ \t]*).*(files([ \t][[][^]]*[\\]])?).*$"
  tags: auth_daemon_config

- name: Create directory for drop-in-unit file for systemd-logind
  ansible.builtin.file:
    path: "/etc/systemd/system/systemd-logind.service.d/"
    state: directory
  tags: logind_set
- name: Allow logind use network connections
  ansible.builtin.blockinfile:
    block: |
      [Service]
      RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6
      IPAddressAllow=192.168.0.0/16
      ProtectHostname=no
    create: true
    path: "/etc/systemd/system/systemd-logind.service.d/override.conf"
  notify:
  - systemd daemon-reload
  - restart logind
  tags: logind_set

- name: Add sudo over ldap into /etc/nsswitch.conf
  ansible.builtin.lineinfile:
    path: "/etc/nsswitch.conf"
    regexp: "^ *#? *sudoers"
    line: "sudoers:    {{ auth_daemon | regex_replace(\"sssd\",\"sss\") }} files"
    state: present
  when: ldap_sudo is defined
  tags: ldap_client_config,ldap_setup_sudo
