---

- name: install auth services`
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: auth_install

- name: check if local CA is exist on target host
  ansible.builtin.stat:
    path: "{{ common_ssl_CA }}"
  register: stat_ssl_ca
  tags: auth_ssl

- name: copy root CA to target host
  ansible.builtin.copy:
    src: "{{ common_local_store }}//{{ common_domain_name }}-ssl-ca.pem"
    dest: "{{ common_ssl_CA }}"
    owner: "root"
    group: "root"
    mode: 0644
  when: ! stat_ssl_ca.stat.exists
  tags: auth_ssl

- name: setup server
  ansible.builtin.import_tasks: ldap_server.yml
  when: ldap_is_server is defined and ldap_is_server | bool
  tags: ldap_server_config

- name: edit {{ ldap_config_dir }}/ldap.conf (system config)
  ansible.builtin.lineinfile:
    path:  "{{ ldap_config_dir }}/ldap.conf"
    regexp: "^[\t ]*#?[\t ]*{{ item.key }}.*"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop: "{{  lookup('ansible.builtin.dict', ldap_conf_params, wantlist=True) }}"
  tags: ldap_client_config

- name: edit /etc/ldap.conf (any services and users config)
  ansible.builtin.lineinfile:
    path:  "/etc/ldap.conf"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    owner: 'root'
    group: 'root'
    mode: '0600'
    create: true
  loop: "{{ ldap_conf_params | ansible.builtin.combine(ldap_user_conf_params) | dict2items }}"
  tags: ldap_client_config

- name: configure auth service if auth_type is not ldap
  ansible.builtin.include_tasks: "{{ auth_type }}.yml" 
  when: auth_type != "ldap"
  tags: auth_service_setup

- name: configure auth mech if auth_mech is not ldap
  ansible.builtin.include_tasks: "{{ auth_mech }}.yml" 
  when: auth_mech != "ldap"
  tags: auth_mech_setup

- name: add passwd/shadow/group over {{ auth_mech }} into /etc/nsswitch.conf
  ansible.builtin.lineinfile:
    path: "/etc/nsswitch.conf"
    regexp: "{{ item }}"
    line: '\1:\2{{ auth_mech }} \3'
    state: present
    backrefs: yes
  loop:
    - "^(passwd):([ \t]*).*(files).*$"
    - "^(shadow):([ \t]*).*(files([ \t][[][^]]*[\\]])?).*$"
    - "^(group):([ \t]*).*(files([ \t][[][^]]*[\\]])?).*$"
  tags: auth_mech_config

- name: add sudo over ldap into /etc/nsswitch.conf
  ansible.builtin.lineinfile:
    path: "/etc/nsswitch.conf"
    regexp: "^ *#? *sudoers"
    line: "sudoers:    ldap files"
    state: present
  when: ldap_sudo is defined
  tags: ldap_client_config,ldap_setup_sudo

