---

- name: load OS-specific variables
  ansible.builtin.include_vars:
    dir: "{{ ldap_vars_dir }}"
    file: "{{ ansible_os_family }}.yml"
  tags: ldap_install

- name: install ldap service
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: ldap_install

- name: check if local CA is exist on target host
  ansible.builtin.stat:
    path: "{{ common_ssl_CA }}"
  register: stat_ssl_ca
  tags: ldap_ssl

- name: copy root CA to target host
  ansible.builtin.copy:
    src: "{{ common_local_store }}//{{ common_domain_name }}-ssl-ca.pem"
    dest: "{{ common_ssl_CA }}"
    owner: "root"
    group: "root"
    mode: 0644
  when: ! stat_ssl_ca.stat.exists
  tags: ldap_ssl

- name: setup server
  ansible.builtin.import_tasks: ldap_server.yml
  when: ldap_is_server is defined and ldap_is_server | bool
  tags: ldap_server_config

- name: edit {{ ldap_config_dir }}/ldap.conf (system config)
  ansible.builtin.lineinfile:
    path:  "{{ ldap_config_dir }}/ldap.conf"
    regexp: "^[\t ]*#?[\t ]*{{ item.key }}.*"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop: "{{  lookup('ansible.builtin.dict', ldap_conf_params, wantlist=True) }}"
  tags: ldap_client_config

- name: edit /etc/ldap.conf (any services and users config)
  ansible.builtin.lineinfile:
    path:  "/etc/ldap.conf"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    owner: 'root'
    group: 'root'
    mode: '0600'
    create: true
  loop: "{{ ldap_conf_params | ansible.builtin.combine(ldap_user_conf_params) | dict2items }}"
  tags: ldap_client_config

- name: edit /etc/nsswitch.conf
  ansible.builtin.lineinfile:
    path: "/etc/nsswitch.conf"
    regexp: "^ *#? *sudoers"
    line: "sudoers:    ldap files"
    state: present
  when: ldap_sudo is defined
  tags: ldap_client_config,ldap_setup_sudo

