---

- name: check if openldap is installed
  community.general.portage:
    package: "{{ auth_packages }}"
    state: present
  tags: auth_install

- name: configure slapd daemon
  block:
    - name: disable slapd.conf
      ansible.builtin.lineinfile:
        path: /etc/conf.d/slapd
        regexp: '^#?\s*(OPTS_CONF="-f /etc/.*/slapd.conf)'
        line: '#\1'
        backrefs: yes
    - name: enable olc config
      ansible.builtin.lineinfile:
        path: /etc/conf.d/slapd
        regexp: '^#?\s*(OPTS_CONF="-F /etc/.*/slapd.d")'
        line: '\1'
        backrefs: yes
  tags: ldap_install_config
  when: ldap_is_server is defined and ldap_is_server | bool

