---
- name: Copy sssd.conf to target host
  ansible.builtin.template:
    src: "{{ auth_templates_dir }}/sssd.conf.j2"
    dest: "/etc/sssd/sssd.conf"
    owner: "root"
    group: "root"
    mode: "0600"
  notify:
    - Enable sssd
    - Restart sssd
  tags: auth_daemon_config,sssd_daemon_config

- name: Delete any modules support from /etc/pam.d/ files
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: "{{ item }}"
    state: absent
  loop: "{{ auth_disable_modules }}"
  tags: auth_daemon_config,sssd_pam_config,sssd_pam_rm_mods

- name: Edit /etc/pam.d/system-auth
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    line: "{{ item.line }}"
    insertbefore: "{{ item.regexp }}"
  loop: "{{ sss_pam_settings }}"
  tags: auth_daemon_config,sssd_pam_config,sssd_pam_add_mods
