---

- name: set sssd_services from host, group, all groups and default values
  set_fact:
    sssd_services: "{{ sssd_services_default | community.general.lists_mergeby(sssd_services_group_all | default([]), sssd_services_group | default([]), sssd_services_host | default([]), 'name', recursive=true) }}"
  tags: auth_mech_config,daemon_config,pam_config

- name: set sssd_domains from group and default values
  set_fact:
    sssd_domains: "{{ sssd_domains_default | community.general.lists_mergeby(sssd_domains_group | default([]), 'name', recursive=true)}}"
  tags: auth_mech_config,daemon_config,pam_config

- name: copy sssd.conf to target host
  ansible.builtin.template:
    src: "{{ auth_templates_dir }}/sssd.conf.j2"
    dest: "/etc/sssd/sssd.conf"
    owner: "root"
    group: "root"
    mode: 0600
  notify:
    - enable sssd
    - restart sssd
  tags: auth_mech_config,daemon_config

- name: delete LDAP support from /etc/pam.d/ files
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: ".*pam_ldap.*"
    state: absent
  tags: auth_mech_config,pam_config

- name: delete Kerberos support from /etc/pam.d/ files
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: ".*pam_krb5.*"
    state: absent
  tags: auth_mech_config,pam_config

- name: delete exist sss support from /etc/pam.d/ files
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: ".*pam_sss.*"
    state: absent
  tags: auth_mech_config,pam_config

- name: edit /etc/pam.d/system-auth
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    line: "{{ item.line }}"
    insertbefore: "{{ item.regexp }}"
  loop: "{{ sss_pam_settings }}"
  tags: auth_mech_config,pam_config


