---

- name: copy sssd.conf to target host
  ansible.builtin.template:
    src: "{{ auth_templates_dir }}/sssd.conf.j2"
    dest: "/etc/sssd/sssd.conf"
    owner: "root"
    group: "root"
    mode: 0600
  notify:
    - enable sssd
    - restart sssd
  tags: auth_mech_config

- name: delete LDAP support from /etc/pam.d/ files
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: ".*pam_ldap.*"
    state: absent
  tags: auth_mech_config

- name: delete Kerberos support from /etc/pam.d/ files
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: ".*pam_krb5.*"
    state: absent
  tags: auth_mech_config

- name: edit /etc/pam.d/system-auth
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    line: "{{ item.line }}"
    insertbefore: "{{ item.regexp }}"
  tags: auth_mech_config
  loop:
    - { regexp: "^auth.*pam_unix.so.*nullok", line: "auth\t\tsufficient\tpam_sss.so use_first_pass" }
    - { regexp: "^account.*pam_unix.so.*", line: "account\t\tsufficient\tpam_sss.so" }
    - { regexp: "^password.*pam_unix.so.*", line: "password\t\tsufficient\tpam_sss.so" }
    - { regexp: "^session.*pam_unix.so.*", line: "session\t\tsufficient\tpam_sss.so" }


